#!/bin/bash

case $1 in
    run)
	ruby main.rb
	;;
    test)
	
	echo "test"

	echo
	ruby ./test/compress_test.rb
	ruby ./test/sensor_network_test.rb

	;;
#	echo $TEST_FILE;;
#	ruby "./test/" + $2
	
    doc)
	echo "doc"
	rm -rf doc
	rdoc --exclude test
	;;
    *)
	echo "that option is not recognized"
	echo "we need a commmand 'test'  or 'doc' or 'run'";;
esac